package ai

import (
	"context"
	"fmt"
)

type MockProvider struct{}

func (MockProvider) GenerateSellingPoints(ctx context.Context, req SellingPointRequest) (*SellingPointResult, error) {
	if req.ProductName == "" {
		return nil, fmt.Errorf("product name is required")
	}
	audience := req.Audience
	if audience == "" {
		audience = "target users"
	}
	return &SellingPointResult{
		Points: []string{
			fmt.Sprintf("%s for %s", req.ProductName, audience),
			"Scenario-based selling point generated by mock provider",
		},
	}, nil
}

func (MockProvider) GenerateBusinessReview(ctx context.Context, req BusinessReviewRequest) (*BusinessReviewResult, error) {
	if req.WindowDays <= 0 {
		return nil, fmt.Errorf("window days must be positive")
	}
	return &BusinessReviewResult{
		Diagnosis: "Mock diagnosis: traffic is available, conversion needs validation.",
		NextSteps: []string{
			"Review SKU display order",
			"Compare refund reasons with selling points",
		},
	}, nil
}
