from dataclasses import dataclass


@dataclass(frozen=True)
class SellingPointRequest:
    product_name: str
    audience: str


@dataclass(frozen=True)
class BusinessReviewRequest:
    window_days: int
    gmv: int = 0
    refund_rate: float = 0.0


class MockAIProvider:
    def generate_selling_points(self, request: SellingPointRequest) -> list[str]:
        if not request.product_name:
            raise ValueError("product_name is required")
        audience = request.audience or "target users"
        return [
            f"{request.product_name} for {audience}",
            "Scenario-based selling point generated by mock provider",
        ]

    def generate_business_review(self, request: BusinessReviewRequest) -> dict[str, object]:
        if request.window_days <= 0:
            raise ValueError("window_days must be positive")
        return {
            "diagnosis": "Mock diagnosis: traffic is available, conversion needs validation.",
            "next_steps": [
                "Review SKU display order",
                "Compare refund reasons with selling points",
            ],
            "window_days": request.window_days,
            "gmv": request.gmv,
            "refund_rate": request.refund_rate,
        }
