name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Print changelog
        run: sed -n '1,120p' CHANGELOG.md
