# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.ai.v1 import ai_pb2 as ai_dot_v1_dot_ai__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ai/v1/ai_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIGenerationServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateSellingPoints = channel.unary_unary(
                '/ai.v1.AIGenerationService/GenerateSellingPoints',
                request_serializer=ai_dot_v1_dot_ai__pb2.GenerateSellingPointsRequest.SerializeToString,
                response_deserializer=ai_dot_v1_dot_ai__pb2.GenerateSellingPointsResponse.FromString,
                _registered_method=True)
        self.GenerateBusinessReview = channel.unary_unary(
                '/ai.v1.AIGenerationService/GenerateBusinessReview',
                request_serializer=ai_dot_v1_dot_ai__pb2.GenerateBusinessReviewRequest.SerializeToString,
                response_deserializer=ai_dot_v1_dot_ai__pb2.GenerateBusinessReviewResponse.FromString,
                _registered_method=True)


class AIGenerationServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GenerateSellingPoints(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateBusinessReview(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIGenerationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateSellingPoints': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateSellingPoints,
                    request_deserializer=ai_dot_v1_dot_ai__pb2.GenerateSellingPointsRequest.FromString,
                    response_serializer=ai_dot_v1_dot_ai__pb2.GenerateSellingPointsResponse.SerializeToString,
            ),
            'GenerateBusinessReview': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateBusinessReview,
                    request_deserializer=ai_dot_v1_dot_ai__pb2.GenerateBusinessReviewRequest.FromString,
                    response_serializer=ai_dot_v1_dot_ai__pb2.GenerateBusinessReviewResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai.v1.AIGenerationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai.v1.AIGenerationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIGenerationService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateSellingPoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.v1.AIGenerationService/GenerateSellingPoints',
            ai_dot_v1_dot_ai__pb2.GenerateSellingPointsRequest.SerializeToString,
            ai_dot_v1_dot_ai__pb2.GenerateSellingPointsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateBusinessReview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.v1.AIGenerationService/GenerateBusinessReview',
            ai_dot_v1_dot_ai__pb2.GenerateBusinessReviewRequest.SerializeToString,
            ai_dot_v1_dot_ai__pb2.GenerateBusinessReviewResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
